### ISSUE TITLE
想要解锁神庙传送的话后面的数字应该改成多少？

### ISSUE THREAD

**Issue by yayk0** [kailous/Botw-Savediter#2]
麻烦作者了
试了1 2 3 4 都是只有标记不能传送
不知道怎么改可以直接传送
还有地图塔如何修改解锁？

**Comment by yayk0** [comment]
找到设置了 地图塔打开MapTower_0xx 的选项即可解锁 
Open_Dungeonxxx解锁神庙
同时需要在去过的地方dungeon和tower设置数值（设置3就可以 别的没试）

**Comment by kailous** [comment]
使用的问题，目前这么高级的，我都还没有用过。
我只是汉化了，并优化了 界面。使用的问题 你可以看看原作者
