### ISSUE TITLE
在存档中添加大师剑【终极】会导致大师剑消失不见

### ISSUE THREAD

**Issue by tubby233** [kailous/Botw-Savediter#3]
将存档内的大师剑修改为大师剑【终极】后进入游戏，游戏内背包、武器栏均找不到大师剑（无论是普通的还是终极），在大师剑祭坛会弹出大师之剑已沉眠，按照网上说的等待十分钟后依旧没有恢复，但重新把存档拖到修改器里查看，是有一把大师剑【终极】的，这该怎么办？

**Comment by kailous** [comment]
因为 修改器是别人写的 我只是汉化了，优化了界面。
修改的问题你要问下原作者，记得用英语。
修改之前 记得备份哦。
